//Масть карт
#define CROSSES		3
#define	PINOCHELE	2
#define	HEARTS		1
#define	BUBI		0

//Значение карты
#define SIX	0
#define SEVEN	4
#define EIGHT	8
#define NINE	12
#define TEN	16
#define JACK	20
#define QUEEN	24
#define KING	28
#define ACE	32

//Полное значение карты
//Шестёрки
#define	SIX_CROSSES	SIX+CROSSES
#define	SIX_PINOCHELE	SIX+PINOCHELE
#define	SIX_HEARTS	SIX+HEARTS
#define	SIX_BUBI	SIX+BUBI
//Семёрки
#define	SEVEN_CROSSES	SEVEN+CROSSES
#define	SEVEN_PINOCHELE	SEVEN+PINOCHELE
#define	SEVEN_HEARTS	SEVEN+HEARTS
#define	SEVEN_BUBI	SEVEN+BUBI
//Восмёрки
#define	EIGHT_CROSSES	EIGHT+CROSSES
#define	EIGHT_PINOCHELE	EIGHT+PINOCHELE
#define	EIGHT_HEARTS	EIGHT+HEARTS
#define	EIGHT_BUBI	EIGHT+BUBI
//Девятки
#define	NINE_CROSSES	NINE+CROSSES
#define	NINE_PINOCHELE	NINE+PINOCHELE
#define	NINE_HEARTS	NINE+HEARTS
#define	NINE_BUBI	NINE+BUBI
//Десятки
#define	TEN_CROSSES	TEN+CROSSES
#define	TEN_PINOCHELE	TEN+PINOCHELE
#define	TEN_HEARTS	TEN+HEARTS
#define	TEN_BUBI	TEN+BUBI
//Вальты
#define	JACK_CROSSES	JACK+CROSSES
#define	JACK_PINOCHELE	JACK+PINOCHELE
#define	JACK_HEARTS	JACK+HEARTS
#define	JACK_BUBI	JACK+BUBI
//Дамы
#define	QUEEN_CROSSES	QUEEN+CROSSES
#define	QUEEN_PINOCHELE	QUEEN+PINOCHELE
#define	QUEEN_HEARTS	QUEEN+HEARTS
#define	QUEEN_BUBI	QUEEN+BUBI
//Короли
#define	KING_CROSSES	KING+CROSSES
#define	KING_PINOCHELE	KING+PINOCHELE
#define	KING_HEARTS	KING+HEARTS
#define	KING_BUBI	KING+BUBI
//Тузы
#define ACE_CROSSES	ACE+CROSSES
#define	ACE_PINOCHELE	ACE+PINOCHELE
#define	ACE_HEARTS	ACE+HEARTS
#define	ACE_BUBI	ACE+BUBI
